function onShowResult(e) {
    if ($("#showResultButton").attr("disabled", "disabled"), this.isInputsValid()) {
        $("#loading").show(), $("#InstructionWrap").hide();
        var t = $(e).attr("data-url");
        $.ajax({ type: "POST", dataType: "html", url: t, data: { courseCode: $("#courseDropDown").val(), uniqueId: isNaN(parseInt($("#UniqueId").val())) ? 0 : $.trim($("#UniqueId").val()), captcha: $("#Captcha").val(), indexNumber: $("#CenterCode").val() + "/" + $("#SerialNumber").val(), token: $("#Captcha").attr("data-token") }, success: function(e) { $("#SOMInstruction").hide(), $("#SOMInstruction span.office-name").text(""), $("#ResultViewTable").html(e), $("#loading").hide(), $("#showResultButton").removeAttr("disabled"), "errorDiv" != $(e)[0].id ? ($("#printResultButton").removeAttr("disabled"), $("#printResultButton").hasClass("btn-primary") || $("#printResultButton").toggleClass("btn-primary")) : ($("#printResultButton").attr("disabled", "disabled"), $("#printResultButton").hasClass("btn-primary") && $("#printResultButton").toggleClass("btn-primary")), $("#Captcha").val("") }, error: function(e) { $("#loading").hide(), $("#showResultButton").removeAttr("disabled"), $("#ResultViewTable").html($("#SometThingContent").html()) } })
    } else $("#showResultButton").removeAttr("disabled")
}

function isInputsValid() { var e = !0; return "" == $("#courseDropDown").val() && ($("#courseDropDown").closest("div.control").hasClass("has-error") || ($("#courseDropDown").closest("div.control").toggleClass("has-error"), $("#CourseCodeValidation").show("fast")), e = !1), "" == $.trim($("#UniqueId").val()) ? ($("#UniqueId").closest("div.control").hasClass("has-error") || ($("#UniqueId").closest("div.control").toggleClass("has-error"), $("#UniqueId").next("#UIDValidation").find("small").text("UID is mandatory"), $("#UniqueId").val(""), $("#UIDValidation").show("fast")), e = !1) : $.isNumeric($.trim($("#UniqueId").val())) ? $.trim($("#UniqueId").val()).length < 6 && ($("#UniqueId").closest("div.control").hasClass("has-error") || ($("#UniqueId").closest("div.control").toggleClass("has-error"), $("#UniqueId").next("#UIDValidation").find("small").text("Please enter a valid UID"), $("#UIDValidation").show("fast")), e = !1) : ($("#UniqueId").closest("div.control").hasClass("has-error") || ($("#UniqueId").closest("div.control").toggleClass("has-error"), $("#UniqueId").next("#UIDValidation").find("small").text("UID should be numeric"), $("#UIDValidation").show("fast")), e = !1), "" == $.trim($("#CenterCode").val()) && "" == $.trim($("#SerialNumber").val()) ? ($("#IdxNum").hasClass("has-error") || ($("#IdxNum").toggleClass("has-error"), $("#IdxNum").find("#IdxNumValidation").find("small").text("Index Number is mandatory"), $("#CenterCode").val(""), $("#SerialNumber").val(""), $("#IdxNumValidation").show("fast")), e = !1) : $.isNumeric($.trim($("#CenterCode").val())) && $.isNumeric($.trim($("#SerialNumber").val())) ? ($.trim($("#CenterCode").val()).length < 7 || 0 == $.trim($("#SerialNumber").val()).length) && ($("#IdxNum").hasClass("has-error") || ($("#IdxNum").toggleClass("has-error"), $("#IdxNum").find("#IdxNumValidation").find("small").text("Please enter a valid Index Number"), $("#IdxNumValidation").show("fast")), e = !1) : ($("#IdxNum").hasClass("has-error") || ($("#IdxNum").toggleClass("has-error"), $("#IdxNum").find("#IdxNumValidation").find("small").text("Index Number should be numeric"), $("#IdxNumValidation").show("fast")), e = !1), "" == $.trim($("#Captcha").val()) && ($("#Captcha").closest("div.control").hasClass("has-error") || ($("#Captcha").closest("div.control").toggleClass("has-error"), $("#Captcha").val(""), $("#CaptchaValidation").show("fast")), e = !1), e }

function ApplyValidationBorderOutline(e) { $(e).closest("div.control").hasClass("has-error") || $(e).closest("div.control").toggleClass("has-error") }

function RemoveValidationBorderOutline(e) { $(e).closest("div.control").hasClass("has-error") && $(e).closest("div.control").toggleClass("has-error") }
$(document).off("change", "#courseDropDown").on("change", "#courseDropDown", function(e) { "" != this.value && (RemoveValidationBorderOutline(this), $("#CourseCodeValidation").is(":visible") && $("#CourseCodeValidation").hide("fast")) }), $(document).off("keyup", "#CenterCode").on("keyup", "#CenterCode", function(e) { var t = $.trim($(this).val()); "" != t && 7 == t.length && $("#SerialNumber").focus() }), $(document).off("focusout", "#Captcha").on("focusout", "#Captcha", function(e) { "" != $.trim($(this).val()) && (RemoveValidationBorderOutline(this), $("#CaptchaValidation").is(":visible") && $("#CaptchaValidation").hide("fast")) }), $(document).off("focusout", "#UniqueId").on("focusout", "#UniqueId", function(e) { var t = $.trim($(this).val()); "" != t && 7 == t.length && $(this).closest("div.control").hasClass("has-error") && $.isNumeric(t) && ($(this).closest("div.control").toggleClass("has-error"), $("#UIDValidation").is(":visible") && $("#UIDValidation").hide("fast")), "" == t || $.isNumeric(t) ? "" != t && t.length < 7 && (ApplyValidationBorderOutline(this), $("#UniqueId").next("#UIDValidation").find("small").text("Please enter a valid UID"), $("#UIDValidation").show("fast")) : (ApplyValidationBorderOutline(this), $("#UniqueId").next("#UIDValidation").find("small").text("UID should be numeric"), $("#UIDValidation").show("fast")) }), $(document).off("focusout", "#CenterCode").on("focusout", "#CenterCode", function(e) { $.trim($("#SerialNumber").val()); "" == $.trim($("#CenterCode").val()) || $.isNumeric($.trim($("#CenterCode").val())) ? "" != $.trim($("#CenterCode").val()) && $.trim($("#CenterCode").val()).length < 7 && (ApplyValidationBorderOutline($("#IdxNum")), $("#IdxNum").find("#IdxNumValidation").find("small").text("Please enter a valid Index Number"), $("#IdxNumValidation").show("fast")) : (ApplyValidationBorderOutline($("#IdxNum")), $("#IdxNum").find("#IdxNumValidation").find("small").text("Index Number should be numeric"), $("#IdxNumValidation").show("fast")) }), $(document).off("focusout", "#SerialNumber").on("focusout", "#SerialNumber", function(e) {
    var t = $.trim($(this).val()),
        a = $.trim($("#CenterCode").val());
    if ("" != t && "" != a)
        if ($.isNumeric(a) && $.isNumeric(t)) {
            $("#SerialNumber").val(t.padStart(3, 0));
            var i, l = a + "/" + t.padStart(3, 0);
            (i = /^[0-9]{7}\/[0-9]{3}$/).test(l) ? (RemoveValidationBorderOutline($("#IdxNum")), $("#IdxNumValidation").is(":visible") && $("#IdxNumValidation").hide("fast")) : (ApplyValidationBorderOutline($("#IdxNum")), $("#IdxNumValidation").show("fast"), $("#IdxNum").find("#IdxNumValidation").find("small").text("Please enter a valid Index Number"))
        } else ApplyValidationBorderOutline($("#IdxNum")), $("#IdxNum").find("#IdxNumValidation").find("small").text("Index Number should be numeric"), $("#IdxNumValidation").show("fast");
    else if ("" != t)
        if ("" != t && $.isNumeric(t) && $("#SerialNumber").val(t.padStart(3, 0)), (i = /^[0-9]{7}\/[0-9]{3}$/).test(l))
            if ($.isNumeric(a) && $.isNumeric(t)) {
                $("#SerialNumber").val(t.padStart(3, 0));
                l = a + "/" + t.padStart(3, 0);
                i.test(l) ? (RemoveValidationBorderOutline($("#IdxNum")), $("#IdxNumValidation").is(":visible") && $("#IdxNumValidation").hide("fast")) : (ApplyValidationBorderOutline($("#IdxNum")), $("#IdxNumValidation").show("fast"), $("#IdxNum").find("#IdxNumValidation").find("small").text("Please enter a valid Index Number"))
            } else ApplyValidationBorderOutline($("#IdxNum")), $("#IdxNum").find("#IdxNumValidation").find("small").text("Index Number should be numeric"), $("#IdxNumValidation").show("fast");
    else ApplyValidationBorderOutline($("#IdxNum")), $("#IdxNumValidation").show("fast"), $("#IdxNum").find("#IdxNumValidation").find("small").text("Please enter a valid Index Number")
});